apps/core/urls.py
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home1'),
    path('sign_up/', views.RegisterView.as_view(), name='sign_up'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('api/users/', views.GetUsersView.as_view()),
    path('api/users/<int:id>', views.GetUserView.as_view()),
    path('create_post/', views.CreatePostView.as_view(), name='create_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('view_posts/', views.ViewPostListView.as_view(), name='view_post'),

]

url/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('core/', include('apps.core.urls', namespace='core')),
    path('admin/', admin.site.urls),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models
from datetime import datetime, timedelta
from apps.auths.models import CustomUser


class Post(models.Model):

    class Category(models.TextChoices):
        WHEAT = 'WT', 'Пшеница'
        BARLEY = 'BR', 'Ячмень'
        OATS = 'OT', 'Овёс'
        CORN = 'CR', 'Кукуруза'
        RYE = 'RY', 'Рожь'
        RICE = 'RC', 'Рис'
        MILLET = 'ML', 'Просо'
        TRITICALE = 'TT', 'Тритикале'

    owner: CustomUser = models.ForeignKey(
        CustomUser, related_name='posts', on_delete=models.PROTECT,
    )
    title: str = models.CharField(
        verbose_name="Заголовок", max_length=100
    )
    text: str = models.TextField(
        verbose_name="Текст"
    )
    phone: str = models.CharField(
        verbose_name="Номер телефона", max_length=15
    )
    category: str = models.CharField(
        max_length=2, choices=Category.choices, default=Category.WHEAT
    )
    date_created: str = models.DateTimeField(
        verbose_name='Дата создания', auto_now_add=True
    )
    images: str = models.ImageField(
        verbose_name="Изображение", upload_to="post_images/"
    )
    price: str = models.DecimalField(
        verbose_name="Цена", max_digits=10, decimal_places=2
    )

    def __str__(self) -> str:
        return f'{self.title} - {self.get_category_display()}'

apps/core/forms.py
from django import forms
from apps.core.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', 'phone', 'category', 'images', 'price']

apps/core/views.py
from django.urls import reverse, reverse_lazy
from django.views import View
from django.shortcuts import (
    redirect, render, get_object_or_404
)
from django.contrib.auth import (
    authenticate as dj_authenticate,
    login as dj_login,
    logout as dj_logout,
)
from django.contrib.auth.decorators import login_required
from django.views.generic import FormView
from django.core.handlers.wsgi import WSGIRequest
from django.http import JsonResponse, HttpResponse, Http404
from django.core import serializers
from typing import Any
from apps.core.models import Post
from apps.auths.forms import RegisterForm, LoginForm, ProfilePictureUpdateForm
from apps.core.mixin import HttpResponseMixin
from apps.auths.models import CustomUser
import random
import json
from .models import Post
from apps.core.forms import PostForm
from django.views.generic.edit import CreateView
from django.views.generic import ListView


class ViewPostListView(ListView):
    model = Post
    template_name = "core/view_posts.html"
    context_object_name = "posts"
    ordering = ['-date_created']


class CreatePostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = "core/create_post.html"
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        """Autintificate user (owner)"""
        form.instance.owner = self.request.user
        return super().form_valid(form)

@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id, owner=request.user)
    post.delete()
    return redirect('core:profile')

def generation_account():
    """Account is 20 chars"""
    ALL_ACCOUNTS = Post.objects.all()
    new_account = ""
    for _ in range(20):
        new_account += str(random.randint(0, 9))

    if new_account in ALL_ACCOUNTS:
        generation_account()

    return new_account


class RegisterView(FormView):
    template_name = 'registration/sign_up.html'
    form_class = RegisterForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        number = form.cleaned_data.get('phone')
        password = form.cleaned_data.get('password')
        user = CustomUser.objects.create_user(email, number, password)
        dj_login(self.request, user)
        return super().form_valid(form)


class LoginView(FormView):
    template_name = 'registration/login.html'
    form_class = LoginForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = dj_authenticate(email=email, password=password)
        if user:
            dj_login(self.request, user)
        else:
            form.add_error('__all__', 'Invalid data')
            return super().form_invalid(form)
        return super().form_valid(form)


class LogoutView(View):
    def get(self,  request, *args: Any, **kwargs: Any):
        dj_logout(request)
        return redirect(reverse("core:home"))



class ProfileView(HttpResponseMixin, View):
    """Get and edit user account and show user cards"""
    template_name: str = 'core/profile.html'

    def get(self, request: WSGIRequest, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse("login"))
        
        form = ProfilePictureUpdateForm(instance=request.user)

        return self.get_http_response(
            request,
            template_name=self.template_name,
            context={
                'user': request.user,
                'posts': Post.objects.filter(owner=request.user),
                'form': form,
            }
        )

    def post(self, request: WSGIRequest, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse("login"))

        form = ProfilePictureUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse("core:profile"))

        return self.get_http_response(
            request,
            template_name=self.template_name,
            context={
                'user': request.user,
                'posts': Post.objects.filter(owner=request.user),
                'form': form,
            }
        )



# @login_required(login_url=reverse_lazy("login"))
def home(request):
    if request.user.is_authenticated:
        user = request.user
        return render(request, "home.html",
                      {
                          'posts': Post.objects.filter(owner=user)
                      }
                      )
    return render(request, "home.html", {'posts': []})



class GetUsersView(View):
    def get(self, request):
        data = serializers.serialize('json', CustomUser.objects.all())
        return HttpResponse(
            data, content_type='application/json', status=200
        )

    def post(self, request):
        user_data = json.loads(request.body)
        email = user_data.get('email')
        phone = user_data.get('phone')
        password = user_data.get('password')
        try:
            user = CustomUser.objects.create_user(email, phone, password)
        except Exception as e:
            return JsonResponse(
                data={
                    'error': e
                }, status=400)
        data = {
            'user_id': user.id,
            'user_email': user.email,
        }
        return JsonResponse(data, status=201)

    def delete(self, request):
        try:
            user = CustomUser.objects.get(id=501)
        except:
            raise Http404
        CustomUser.objects.delete_model(user)
        return JsonResponse(
            data={'message': "DELETE"},
            status=204,
        )


class GetUserView(View):
    def get(self, request, id):
        data = serializers.serialize(
            'json',
            CustomUser.objects.filter(id=id)
        )
        return HttpResponse(
            data, content_type='application/json', status=200
        )

    def delete(self, request, id):
        try:
            user: CustomUser = CustomUser.objects.get(id=id)
        except:
            raise Http404
        user.objects.delete_model()
        return JsonResponse(
            data={'message': "DELETE"},
            status=204,
        )

apps/core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block my_style %}{% endblock %}

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">


  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <link href="http://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'core/media/5188591442036125206.ico' %}" type="image/x-icon">

  <title>Qoldan Qolga</title>

  <script src="https://kit.fontawesome.com/b3330d82de.js" crossorigin="anonymous" defer></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"
    defer></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"
    defer></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"
    defer></script>

  <script src="{% static 'core/libs/gsap/gsap.min.js' %}" defer></script>
  <script src="{% static 'core/libs/gsap/ScrollTrigger.min.js' %}" defer></script>
  <script src="{% static 'core/libs/gsap/ScrollSmoother.min.js' %}" defer></script>

  <script src="{% static 'core/js/app.js' %}" defer></script>

    <link rel="stylesheet" type="text/css" href="{% static 'core/css/base.css' %}">




</head>



<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:home' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:create_post' %}">Создать пост</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:view_post' %}">Объявления</a>
                    </li>

                </ul>
            </div>
            <div>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <span class="navbar-text">Ваш аккаунт {{ user.email }}</span>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:profile' %}">Профиль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:logout' %}">Выйти</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:login' %}">Войти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:sign_up' %}">Зарегистрироваться</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block cont %}

    {% endblock %}



    <div class="container">
        {% block content %} {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
  <script>
    const menuToggle = document.querySelector('.toggle');
    const showcase = document.querySelector('.showcase');

    menuToggle.addEventListener('click', () => {
      menuToggle.classList.toggle('active');
      showcase.classList.toggle('active');
    })
  </script>

  <script src="http://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>
</body>

</html>

apps/core/templates/base22.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Site{% endblock %}</title>

    <style>

    </style>
</head>

<body>



</body>

</html>

apps/core/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home Page{% endblock %}

{% block cont %}
  <div class="wrapper">
    <div class="content">

      <section class="showcase">
        <header class="head-video">
          <div class="h">
            <h2 class="container logo">Qoldan Qolga</h2>
          </div>
          <div class="toggle"></div>
        </header>
        <video src="{% static 'core/media/4280455-uhd_3840_2160_30fps.mp4' %}" muted loop autoplay></video>
        <div class="overlay"></div>
        <div class="container text">
          <div id="size1">Трейдинговая платформа</div>
          <div id="size2">Покупка, продажа, аренда</div>
          <p>
            Удобный поиск предложений:  <br><br>
            Быстро находите выгодные сделки на покупку и продажу сельхозпродукции. <br><br>
            Становись лучше вместе с нами!
          </p>
          <a href="register.html" target="_blank">Регистрация</a>
        </div>
<!--        <ul class="social">-->
<!--          <li><a href="#"><img src="https://i.ibb.co/x7P24fL/facebook.png"></a></li>-->
<!--          <li><a href="#"><img src="https://i.ibb.co/Wnxq2Nq/twitter.png"></a></li>-->
<!--          <li><a href="#"><img src="https://i.ibb.co/ySwtH4B/instagram.png"></a></li>-->
<!--        </ul>-->
      </section>
      <div class="menu">
        <ul>
          <li><a href="autoris.html" target="_blank">Войти</a></li>
          <li><a href="register.html" target="_blank">Регистрация</a></li>
          <li><a href="kursi.html" target="_blank">Обучение</a></li>
          <li><a href="administrirovanie.html" target="_blank">Администрация</a></li>
          <li><a href="cabinet.html" target="_blank">Личный кабинет</a></li>
          <li><a href="shop.html" target="_blank">Магазин</a></li>
        </ul>
      </div>


      <div class="second-page">

        <header class="hero-section">
          <img data-speed=".6" class="hero" src="" alt="">
          <div class="container">
            <div data-speed=".75" class="main-header">
              <h1 class="main-title">Наши предложения</h1>
            </div>
          </div>
        </header>

        <div class="portfolio">
          <div class="container">
            <main class="gallery">
              <div data-speed=".9" class="gallery__left">

                <img class=" gallery__item" src="{% static 'core/media/pexels-jk04-2933243.jpg' %}" alt="">
                <img class=" gallery__item" src="{% static 'core/media/pexels-tomfisk-1595108.jpg' %}" alt="">

                <div class="text-block gallery__item">
                  <h2 class="text-block__h">Электронные контракты:</h2>
                  <p class="text-block__p">Заключайте сделки онлайн с юридической защитой</p>
                </div>

                <img class=" gallery__item" src="../media/foto3.jpg" alt="">

              </div>
              <div data-speed="1.6" class="gallery__right">

                <div class="text-block gallery__item">
                  <h2 class="text-block__h">Безопасные расчёты:</h2>
                  <p class="text-block__p">Обеспечение прозрачности и защиты платежей между участниками.</p>
                </div>

                <img class=" gallery__item" src="{% static 'core/media/pexels-pixabay-289334.jpg' %}" alt="">
                <img class=" gallery__item" src="{% static 'core/media/pexels-pierre-sudre-9695-55766.jpg' %}" alt="">
                <img class=" gallery__item" src="{% static 'core/media/pexels-karol-wisniewski-279026-878297.jpg' %}" alt="">

                <div class="text-block gallery__item">
                  <h2 class="text-block__h">Личный кабинет: </h2>
                  <p class="text-block__p">Управляйте сделками, документами и отчетностью в одном месте</p>
                </div>



              </div>
            </main>
          </div>
        </div>

      </div>



    </div>
  </div>
{% endblock %}