apps/core/urls.py
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home1'),
    path('sign_up/', views.RegisterView.as_view(), name='sign_up'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('api/users/', views.GetUsersView.as_view()),
    path('api/users/<int:id>', views.GetUserView.as_view()),
    path('create_post/', views.CreatePostView.as_view(), name='create_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('view_posts/', views.ViewPostListView.as_view(), name='view_post'),

]

url/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('core/', include('apps.core.urls', namespace='core')),
    path('admin/', admin.site.urls),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models
from datetime import datetime, timedelta
from apps.auths.models import CustomUser


class Post(models.Model):

    class Category(models.TextChoices):
        WHEAT = 'WT', 'Пшеница'
        BARLEY = 'BR', 'Ячмень'
        OATS = 'OT', 'Овёс'
        CORN = 'CR', 'Кукуруза'
        RYE = 'RY', 'Рожь'
        RICE = 'RC', 'Рис'
        MILLET = 'ML', 'Просо'
        TRITICALE = 'TT', 'Тритикале'

    owner: CustomUser = models.ForeignKey(
        CustomUser, related_name='posts', on_delete=models.PROTECT,
    )
    title: str = models.CharField(
        verbose_name="Заголовок", max_length=100
    )
    text: str = models.TextField(
        verbose_name="Текст"
    )
    phone: str = models.CharField(
        verbose_name="Номер телефона", max_length=15
    )
    category: str = models.CharField(
        max_length=2, choices=Category.choices, default=Category.WHEAT
    )
    date_created: str = models.DateTimeField(
        verbose_name='Дата создания', auto_now_add=True
    )
    images: str = models.ImageField(
        verbose_name="Изображение", upload_to="post_images/"
    )
    price: str = models.DecimalField(
        verbose_name="Цена", max_digits=10, decimal_places=2
    )

    def __str__(self) -> str:
        return f'{self.title} - {self.get_category_display()}'

apps/core/forms.py
from django import forms
from apps.core.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', 'phone', 'category', 'images', 'price']

apps/core/views.py
from django.urls import reverse, reverse_lazy
from django.views import View
from django.shortcuts import (
    redirect, render, get_object_or_404
)
from django.contrib.auth import (
    authenticate as dj_authenticate,
    login as dj_login,
    logout as dj_logout,
)
from django.contrib.auth.decorators import login_required
from django.views.generic import FormView
from django.core.handlers.wsgi import WSGIRequest
from django.http import JsonResponse, HttpResponse, Http404
from django.core import serializers
from typing import Any
from apps.core.models import Post
from apps.auths.forms import RegisterForm, LoginForm, ProfilePictureUpdateForm
from apps.core.mixin import HttpResponseMixin
from apps.auths.models import CustomUser
import random
import json
from .models import Post
from apps.core.forms import PostForm
from django.views.generic.edit import CreateView
from django.views.generic import ListView


class ViewPostListView(ListView):
    model = Post
    template_name = "core/view_posts.html"
    context_object_name = "posts"
    ordering = ['-date_created']


class CreatePostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = "core/create_post.html"
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        """Autintificate user (owner)"""
        form.instance.owner = self.request.user
        return super().form_valid(form)

@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id, owner=request.user)
    post.delete()
    return redirect('core:profile')

def generation_account():
    """Account is 20 chars"""
    ALL_ACCOUNTS = Post.objects.all()
    new_account = ""
    for _ in range(20):
        new_account += str(random.randint(0, 9))

    if new_account in ALL_ACCOUNTS:
        generation_account()

    return new_account


class RegisterView(FormView):
    template_name = 'registration/sign_up.html'
    form_class = RegisterForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        number = form.cleaned_data.get('phone')
        password = form.cleaned_data.get('password')
        user = CustomUser.objects.create_user(email, number, password)
        dj_login(self.request, user)
        return super().form_valid(form)


class LoginView(FormView):
    template_name = 'registration/login.html'
    form_class = LoginForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = dj_authenticate(email=email, password=password)
        if user:
            dj_login(self.request, user)
        else:
            form.add_error('__all__', 'Invalid data')
            return super().form_invalid(form)
        return super().form_valid(form)


class LogoutView(View):
    def get(self,  request, *args: Any, **kwargs: Any):
        dj_logout(request)
        return redirect(reverse("core:home"))



class ProfileView(HttpResponseMixin, View):
    """Get and edit user account and show user cards"""
    template_name: str = 'core/profile.html'

    def get(self, request: WSGIRequest, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse("login"))
        
        form = ProfilePictureUpdateForm(instance=request.user)

        return self.get_http_response(
            request,
            template_name=self.template_name,
            context={
                'user': request.user,
                'posts': Post.objects.filter(owner=request.user),
                'form': form,
            }
        )

    def post(self, request: WSGIRequest, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse("login"))

        form = ProfilePictureUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse("core:profile"))

        return self.get_http_response(
            request,
            template_name=self.template_name,
            context={
                'user': request.user,
                'posts': Post.objects.filter(owner=request.user),
                'form': form,
            }
        )



# @login_required(login_url=reverse_lazy("login"))
def home(request):
    if request.user.is_authenticated:
        user = request.user
        return render(request, "home.html",
                      {
                          'posts': Post.objects.filter(owner=user)
                      }
                      )
    return render(request, "home.html", {'posts': []})



class GetUsersView(View):
    def get(self, request):
        data = serializers.serialize('json', CustomUser.objects.all())
        return HttpResponse(
            data, content_type='application/json', status=200
        )

    def post(self, request):
        user_data = json.loads(request.body)
        email = user_data.get('email')
        phone = user_data.get('phone')
        password = user_data.get('password')
        try:
            user = CustomUser.objects.create_user(email, phone, password)
        except Exception as e:
            return JsonResponse(
                data={
                    'error': e
                }, status=400)
        data = {
            'user_id': user.id,
            'user_email': user.email,
        }
        return JsonResponse(data, status=201)

    def delete(self, request):
        try:
            user = CustomUser.objects.get(id=501)
        except:
            raise Http404
        CustomUser.objects.delete_model(user)
        return JsonResponse(
            data={'message': "DELETE"},
            status=204,
        )


class GetUserView(View):
    def get(self, request, id):
        data = serializers.serialize(
            'json',
            CustomUser.objects.filter(id=id)
        )
        return HttpResponse(
            data, content_type='application/json', status=200
        )

    def delete(self, request, id):
        try:
            user: CustomUser = CustomUser.objects.get(id=id)
        except:
            raise Http404
        user.objects.delete_model()
        return JsonResponse(
            data={'message': "DELETE"},
            status=204,
        )

apps/core/templates/core/create_post.html
{% extends "base.html" %}
{% block content %}
<h2>Создать пост</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

apps/core/templates/core/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mt-5">
        <div class="card shadow-lg p-4">
            <h2 class="text-center mb-4">Profile</h2>

            <div class="text-center">
                {% if user.profile_picture %}
                    <img src="{{ user.profile_picture.url }}" class="rounded-circle" width="150" height="150" alt="Profile Picture">
                {% else %}
                    <img src="{% static 'images/default_profile.png' %}" class="rounded-circle" width="150" height="150" alt="Default Profile">
                {% endif %}
            </div>

            <form method="post" enctype="multipart/form-data" class="mt-3 text-center">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary mt-3">Обновить фото</button>
            </form>

            <ul class="list-group mt-3">
                <li class="list-group-item"><strong>Email:</strong> {{ user.email }}</li>
            </ul>

            <div class="text-center mt-3">
                <a href="{% url 'core:logout' %}" class="btn btn-danger">Выйти</a>
            </div>
        </div>

        {% if posts %}
            <h3 class="mt-5">Ваши посты</h3>
            <div class="row">
                {% for post in posts %}
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <div class="card-body">
                                <h5 class="card-title">{{ post.title }}</h5>
                                <p class="card-text"><strong>Цена:</strong> {{ post.price }}</p>
                                <p class="card-text"><strong>Категория:</strong> {{ post.category }}</p>
                                <a href="{% url 'core:delete_post' post.id %}" class="btn btn-sm btn-danger">Удалить</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p class="mt-4 text-center text-muted">У вас пока нет постов.</p>
        {% endif %}
    </div>
{% endblock %}

apps/core/templates/core/view_posts.html
{% extends "base.html" %}
{% block content %}
<h2>Все объявления</h2>
<div class="container mt-4">
    <div class="row">
        {% for post in posts %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <img src="{{ post.images.url }}" class="card-img-top" alt="{{ post.title }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">{{ post.text|truncatechars:100 }}</p>
                        <p><strong>Цена:</strong> {{ post.price }}₸</p>
                        <p><strong>Категория:</strong> {{ post.get_category_display }}</p>
                        <p><strong>Телефон:</strong> {{ post.phone }}</p>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Объявлений пока нет.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}